### ISSUE TITLE
Curl module doesn't support 'data' or 'data-urlencode'?

### ISSUE THREAD

**Issue by BarnumD** [relay-integrations/relay-stdlib#9]
How would I replicate the following curl example from [Terraform's API](https://www.terraform.io/docs/cloud/api/workspace-variables.html)?  The step.sh file in this repository seems to account for `body`, `headers`, `url`, etc, but not `data` or `data-urlencode`.
```
{
  "data": {
    "type":"vars",
    "attributes": {
      "key":"some_key",
      "value":"some_value",
      "description":"some description",
      "category":"terraform",
      "hcl":false,
      "sensitive":false
    }
  }
}
```
```
curl \
  --header "Authorization: Bearer $TOKEN" \
  --header "Content-Type: application/vnd.api+json" \
  --request POST \
  --data @payload.json \
  https://app.terraform.io/api/v2/workspaces/ws-4j8p6jX1w33MiDC7/vars
```

**Comment by rick-a-lane-ii** [comment]
You should theoretically be able to define this by the following:

```
body:
  data:
    type: vars
    attributes:
      key: some_key
      value: some_value
      description: some description
      category: terraform
      hcl: false
      sensitive: false
```

**Comment by rick-a-lane-ii** [comment]
```
apiVersion: v1

steps:
- name: curl
  image: relaysh/stdlib-step-curl
  spec:
    method: POST
    url: <url>
    expects:
    - 200
    - 201
    headers:
      Content-Type: application/json
      Accept: application/json
      Authorization: ${secrets.auth}
    body:
      data:
        type: vars
        attributes:
          key: some_key
          value: some_value
          description: some description
          category: terraform
          hcl: false
          sensitive: false
```

**Comment by rick-a-lane-ii** [comment]
You can also embed secrets, outputs, or parameters into the `body`, as show below:

```
apiVersion: v1

steps:
- name: curl
  image: relaysh/stdlib-step-curl
  spec:
    method: POST
    url: <url>
    expects:
    - 200
    - 201
    headers:
      Content-Type: application/json
      Accept: application/json
      Authorization: ${'Bearer ' + secrets.auth}
    body:
      data:
        type: vars
        attributes:
          key: ${secrets.key}
          value: ${secrets.value}
          description: some description
          category: terraform
          hcl: false
          sensitive: false
```

Also included an example of prepending `Bearer ` outside the secret value.
